import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { QueryProvider } from "@/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="pt-br" className="*:border-red-500">
        <body className={`antialiased`}>
          {children}
          <ToastContainer theme="dark" position="top-center" />
        </body>
      </html>
    </QueryProvider>
  );
}
